baseURL = 'https://fmz.pw'
languageCode = 'en-us'
title = 'Frank Marazita'
pluralizeListTitles = false

[params]

# Appearance settings

theme = 'auto'
colorPalette = 'eink'
hideHeader = true

# Intro on main page, content in markdown

homeIntroTitle = 'Hey!'
homeIntroContent = """

I'm Frank, a Senior Software Engineer in Melbourne, Australia.

I've worked across startups, scale-ups, and corporate environments building full stack systems and cloud infrastructure - from bleeding edge to legacy. I enjoy product engineering, developer experience, and security.

Outside of work, I tinker with my homelab, work on side projects, and mess with electronics and 3D printing. I also enjoy mentoring junior developers and attending community tech events.

(and try make good coffee ☕)

I occasionally write about software development and things I'm working on. Check out my [blog](/blog) or see what I'm [building](/projects). [RSS available](/index.xml).

Feel free to get in contact! ✌️
"""

singleDateFormat = '02 Jan 2006'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons

[[params.social]]
name = "email"
url = "mailto:me@fmz.pw"

[[params.social]]
name = "github"
url = "https://github.com/frankmarazita"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/frank-marazita/"

[[params.social]]
name = "signal"
url = "https://signal.me/#eu/TgpLTwrWAyA5eCYyLwiMJLHR1_Zf1mTNhFvszj3T5JBlzptHfp5Az4_AHZPb21vE"

# Main menu pages

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/blog"

[[params.menu]]
name = "blognotes"
url = "/blognotes"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "gear"
url = "/gear"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

# Syntax highlight on code blocks

[markup]
[markup.highlight]
style = 'bw'
