baseURL = 'https://fmz.pw'
languageCode = 'en-us'
title = 'Frank Marazita'
pluralizeListTitles = false

[params]

# Appearance settings

theme = 'auto'
colorPalette = 'eink'
hideHeader = true

# Intro on main page, content in markdown

homeIntroTitle = 'Hey!'
homeIntroContent = """

Iâ€™m Frank, a software engineer based in Melbourne, Australia. I hold a Bachelor's degree from [RMIT University](https://www.rmit.edu.au/) and currently work as a Senior Software Engineer.

Here, I write about software development, productivity, and personal growth, driven by my passion for learning and sharing knowledge.

Feel free to get in contact!
"""

singleDateFormat = '02 Jan 2006'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '02 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons

[[params.social]]
name = "email"
url = "mailto:me@fmz.pw"

[[params.social]]
name = "github"
url = "https://github.com/frankmarazita"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/frank-marazita/"

[[params.social]]
name = "signal"
url = "https://signal.me/#eu/TgpLTwrWAyA5eCYyLwiMJLHR1_Zf1mTNhFvszj3T5JBlzptHfp5Az4_AHZPb21vE"

# Main menu pages

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "blog"
url = "/blog"

[[params.menu]]
name = "blognotes"
url = "/blognotes"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "gear"
url = "/gear"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]

# Syntax highlight on code blocks

[markup]
[markup.highlight]
style = 'bw'
